INSERT INTO role(name, description) VALUES ('USER' , 'User role');
INSERT INTO role(name, description) VALUES ('ADMIN' , 'Admin role');
INSERT INTO tag(name, description) VALUES ('HTML&CSS' , 'HTML & CSS');
INSERT INTO tag(name, description) VALUES ('REACT' , 'React');
INSERT INTO tag(name, description) VALUES ('ANGULAR' , 'Angular');
INSERT INTO tag(name, description) VALUES ('VUE' , 'Vue');
INSERT INTO tag(name, description) VALUES ('SPRING' , 'Spring');
INSERT INTO tag(name, description) VALUES ('JAVA' , 'Java');
INSERT INTO tag(name, description) VALUES ('JAVASCRIPT' , 'Javascript');
INSERT INTO tag(name, description) VALUES ('HIBERNATE' , 'Hibernate');
INSERT INTO ob_user(username, password, email) VALUES ('Admin' , '$2a$10$bPkErVt0Zii5mRrN4wfU2OeMGxzvvD3CgWzFdOiQgSOGMiknJUfam' , 'admin@ob.com');
INSERT INTO ob_user(username, password, email) VALUES ('Admin1' , '$2a$10$bPkErVt0Zii5mRrN4wfU2OeMGxzvvD3CgWzFdOiQgSOGMiknJUfam' , 'easyfa21@gmail.com');
INSERT INTO ob_user(username, password, email) VALUES ('Álex' , '$2a$10$bPkErVt0Zii5mRrN4wfU2OeMGxzvvD3CgWzFdOiQgSOGMiknJUfam' , 'alex@ob.com');
INSERT INTO ob_user(username, password, email) VALUES ('Jesús' , '$2a$10$bPkErVt0Zii5mRrN4wfU2OeMGxzvvD3CgWzFdOiQgSOGMiknJUfam' , 'jesus@ob.com');
INSERT INTO user_roles(user_id, role_id) VALUES (1 , 1);
INSERT INTO user_roles(user_id, role_id) VALUES (1 , 2);
INSERT INTO user_roles(user_id, role_id) VALUES (2 , 1);
INSERT INTO user_roles(user_id, role_id) VALUES (2 , 2);
INSERT INTO user_roles(user_id, role_id) VALUES (3 , 1);
INSERT INTO user_roles(user_id, role_id) VALUES (3 , 2);
INSERT INTO user_roles(user_id, role_id) VALUES (4 , 1);
INSERT INTO user_roles(user_id, role_id) VALUES (4 , 2);
INSERT INTO student(name, email, phone, country, location, mobility, remote, picture_id, resume_id, user_id) VALUES ('Dwight Schrute', 'dschrute@ob.com', '+1 570-348-4100', 'Estados Unidos', 'Scranton', true, 0, null, null, 1);
INSERT INTO student(name, email, phone, country, location, mobility, remote, picture_id, resume_id, user_id) VALUES ('Paco Lobaton', 'plobaton@ob.com', '+34 652318997', 'España', 'Jerez de la Frontera', true, 1, null, null, 1);
INSERT INTO student(name, email, phone, country, location, mobility, remote, picture_id, resume_id, user_id) VALUES ('Ibai Llanos', 'illanos@ob.com', '+34 657895886', 'España', 'Bilbao', false, 1, null, null, 1);
INSERT INTO student(name, email, phone, country, location, mobility, remote, picture_id, resume_id, user_id) VALUES ('Matías Prats', 'mprats@ob.com', '+34 611234054', 'España', 'Madrid', false, 0, null, null, 1);
INSERT INTO student_tags(student_id, tag_id) VALUES (1 , 1);
INSERT INTO student_tags(student_id, tag_id) VALUES (1 , 2);
INSERT INTO student_tags(student_id, tag_id) VALUES (1 , 3);
INSERT INTO student_tags(student_id, tag_id) VALUES (1 , 4);
INSERT INTO student_tags(student_id, tag_id) VALUES (1 , 7);
INSERT INTO student_tags(student_id, tag_id) VALUES (2 , 5);
INSERT INTO student_tags(student_id, tag_id) VALUES (2 , 6);
INSERT INTO student_tags(student_id, tag_id) VALUES (2 , 8);
INSERT INTO student_tags(student_id, tag_id) VALUES (3 , 3);
INSERT INTO student_tags(student_id, tag_id) VALUES (3 , 7);
INSERT INTO student_tags(student_id, tag_id) VALUES (4 , 2);

